### ISSUE TITLE
Plugin activation failed: TypeError: project.getCurrentDirectory is not a function

### ISSUE THREAD

**Issue by jerrywang1981** [neoclide/coc-tslint-plugin#2]
what could be the problem? Thanks a lot.

> Info 0    [20:44:8.346] Binding...
Info 1    [20:44:8.360] request: {"seq":0,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true}}}
Perf 2    [20:44:8.361] 0::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.9501
Info 3    [20:44:8.361] response: {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":0,"success":true,"body":true}
Info 6    [20:44:8.363] Config file name: /Users/jerry/repo/webapp_angular/tsconfig.json
Info 7    [20:44:8.608] Local plugin loading enabled; adding /users/jerry/repo/webapp_angular to search paths
Info 8    [20:44:8.608] Enabling plugin typescript-tslint-plugin from candidate paths: /users/jerry/repo/webapp_angular,/Users/jerry/repo/webapp_angular/node_modules/typescript/lib/tsserver.js/../../..,/Users/jerry/.config/coc/extensions/node_modules/coc-tslint-plugin
Info 9    [20:44:8.608] Loading typescript-tslint-plugin from /users/jerry/repo/webapp_angular (resolved to /users/jerry/repo/webapp_angular/node_modules)
Info 10   [20:44:8.899] [typescript-tslint-plugin] "Create"
Info 11   [20:44:8.899] [typescript-tslint-plugin] "ConfigurationManager: Found configured project: /Users/jerry/repo/webapp_angular/tsconfig.json"
Info 12   [20:44:8.900] Plugin activation failed: TypeError: project.getCurrentDirectory is not a function

**Comment by chemzqm** [comment]
Looks like your  typescript-tslint-plugin module is outdated.

**Comment by jerrywang1981** [comment]
no, it's not typescript-tslint-plugin issue, It looked like typescript version in my project package.json is low and I upgraded to latest version, now it works, thank you.
