### ISSUE TITLE
Quickfix provider

### ISSUE THREAD

**Issue by jerrywang1981** [neoclide/coc-tslint-plugin#3]
I have the problem that the TSLint errors are not fixed automatically when I save the buffer. it worked if I install coc-tslint, but not coc-tslint-plugin, I did some debugging in the code and found there was no code action for it, e.g. 

> //this is comment
console.log('ok')

these two lines of code, it should 
* add a whitespace in the comment 
* and add ; to the end of second line, 

but there is no Quickfix for second line, and add something //disable next line for the first line 'comment TSLint error', as this worked in coc-tslint but not in coc-tslint-plugin, should I install some package?

**Comment by chemzqm** [comment]
Use codeAction, if there's no codeAction, it's bug of your tslint or your local `typescript-tslint-plugin` module.

**Comment by vcfvct** [comment]
Having the same issue, no option to add `;` to the end of the line after triggering `codeAction`. @jerrywang1981 , any luck on fixing it?

**Comment by chemzqm** [comment]
> no option to add ; to the end of the line after triggering

I believe there's no such kind of quickfix action, send your feature request to typescript-tslint-plugin.
