### ISSUE TITLE
How do I get coc to fix the current file? 

### ISSUE THREAD

**Issue by bag-man** [neoclide/coc-tslint-plugin#6]
If I enable `"tslint.autoFixOnSave": true` in my `coc-settings.json`, the plugin will autofix my current file on save. However this can cause some problems on occasion, so I would rather run the autofix manually. 

However I can't seem to figure out what command I should run. If I run `:CocAction` I can see `Fix all auto-fixable tslint failures [tsserver]`, so it is a command that can be ran, but I have to select it in the menu. 

Thanks!

**Comment by zachkirsch** [comment]
+1

**Comment by chemzqm** [comment]
Read vim help

**Comment by zachkirsch** [comment]
Thank you for that incredibly helpful reply @chemzqm!

**Comment by shivangp76** [comment]
Any update on this?

**Comment by chemzqm** [comment]
You can invoke codeAction by title

**Comment by giovannibenussi** [comment]
I was able to make it work by running `:CocCommand eslint.executeAutofix`. I added the following code to my vimrc file to assign it a custom mapping:

```sh
nmap <leader><leader>f  :CocCommand eslint.executeAutofix<cr>
```
